name: Build via build.sh with VCPKG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.arch }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Enable QEMU (for ARM64)
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git curl unzip tar

      - name: Run build.sh
        run: ./build.sh
