name: Build with vcpkg and CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [x64-linux, arm64-linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build g++ gcc cmake make

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'
          vcpkgGitCommitId: 'latest'

      - name: Install dependencies for matrix triplet
        run: |
          ./vcpkg/vcpkg install --triplet ${{ matrix.arch }}

      - name: Configure and build with CMake
        run: |
          mkdir -p build
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=/usr/bin/gcc \
            -DCMAKE_CXX_COMPILER=/usr/bin/g++ \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j$(nproc)
