name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for ${{ matrix.arch }}
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --build-arg TARGET_ARCH=${{ matrix.arch }} \
            -t gompeivision-build:${{ matrix.arch }} \
            --load .

      - name: Create output directory
        run: mkdir -p build_output

      - name: Run build container and copy binary out
        run: |
          container_id=$(docker create gompeivision-build:${{ matrix.arch }})
          docker start -a $container_id
          docker cp $container_id:/workspace/build ./build_output/${{ matrix.arch }}
          docker rm $container_id

      - name: Upload build artifact for ${{ matrix.arch }}
        uses: actions/upload-artifact@v3
        with:
          name: gompeivision-build-${{ matrix.arch }}
          path: build_output/${{ matrix.arch }}/build
