name: Build GompeiVision

on:
  push:
  pull_request:

jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build for x86_64
        run: |
          docker build --build-arg TARGET_ARCH=amd64 -t gompeivision:x86_64 .
          docker run --rm gompeivision:x86_64 cp /workspace/build/gompeivision /workspace/gompeivision-x86_64
      - uses: actions/upload-artifact@v3
        with:
          name: gompeivision-x86_64
          path: gompeivision-x86_64

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build for arm64
        run: |
          docker build --build-arg TARGET_ARCH=arm64 -t gompeivision:arm64 .
          docker run --rm gompeivision:arm64 cp /workspace/build/gompeivision /workspace/gompeivision-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: gompeivision-arm64
          path: gompeivision-arm64
