name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build x86
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.X86
          push: false
          tags: gompeivision:x86

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.X86.arm64
          platform: linux/arm64
          push: false
          tags: gompeivision:arm64
